FROM mcr.microsoft.com/dotnet/runtime:6.0
COPY  C:/Users/Smile/source/repos/RealTimeWeatherMonitoring/RealTimeWeatherMonitoring/bin/Release/net6.0/publish .
ENTRYPOINT ["dotnet","RealTimeWeatherMonitoring.dll"]
